
'use client';

import NextLink from 'next/link';
import { Button } from '@/components/ui/button';
import BrandLogoIcon from '@/components/icons/BrandLogoIcon';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { useEffect, useState } from 'react';
import { cn } from '@/lib/utils';

const faqData = [
  {
    question: "What are these AI crawlers and scrapers you're talking about?",
    answer: (<><p>They're automated software scripts that roam the internet. Some are legitimate, like search engine crawlers (Googlebot, Bingbot). Many others are a nuisance or outright malicious. Think content scrapers stealing your articles, price bots undercutting your store, spambots filling your forms, vulnerability scanners looking for weaknesses, or just aggressive bots hogging your server resources and slowing your site down for real people.</p></>)
  },
  {
    question: "Realistically, what damage can these unwanted crawlers do to my website?",
    answer: (
      <>
        <p>More than you might think.</p>
        <ul className="list-disc pl-5 space-y-1 mt-2 text-foreground/80">
          <li><strong>Increased Server Load & Higher Costs:</strong> They consume your bandwidth and CPU, potentially making your site sluggish for actual users and driving up your hosting expenses.</li>
          <li><strong>Content & Data Theft:</strong> Your original blog posts, product descriptions, images, or pricing can be lifted and reused elsewhere, hurting your SEO and competitive edge.</li>
          <li><strong>Skewed Analytics:</strong> Bot traffic makes it hard to understand who your real audience is and how they behave, messing up your marketing data.</li>
          <li><strong>Spam & Annoyance:</strong> Flooding contact forms, comment sections, or attempting fake sign-ups.</li>
          <li><strong>Reconnaissance for Attacks:</strong> Some bots are purely scanning for outdated software or security holes to exploit. While SpiteSpiral is primarily a deterrent for nuisance bots, reducing their presence can sometimes limit this initial probing.</li>
        </ul>
      </>
    )
  },
  {
    question: "What exactly is a Tarpit and how does it stop them?",
    answer: (<><p>Imagine digital flypaper for bots. When a crawler accesses one of our Managed URLs that you've placed on your site, our SpiteSpiral tarpit servers—powered by our proprietary Nightmare v2 engine—deliberately engage with it very, very slowly. We might feed it thematically coherent, N-gram generated text at a snail's pace, send it an endless stream of procedurally generated unique pages, or make it think it's found something interesting that requires many slow requests. The goal isn't to block it with a "403 Forbidden" (it might just try again from a different IP), but to waste its time and computational resources, making your site an incredibly inefficient and frustrating target.</p></>)
  },
   {
    question: "How is SpiteSpiral different from `robots.txt` or my firewall/WAF?",
    answer: (<><p><code className="bg-muted px-1.5 py-0.5 rounded-sm">Robots.txt</code> is a request, not a command, and many AI scrapers and malicious bots ignore it. Firewalls and WAFs are great for blocking known threats or patterns, but persistent, adaptive scrapers can often find ways around them. SpiteSpiral is what happens *next*. We're designed to specifically target and neutralize the bots that bypass these first lines of defense, making their journey not just blocked, but incredibly inefficient and counterproductive by drawing them into resource-intensive, procedurally generated layouts filled with thematically coherent N-gram text.</p></>)
  },
  {
    question: "Will using SpiteSpiral hurt my website's SEO?",
    answer: (<><p>Not when implemented correctly. SpiteSpiral is designed to be invisible to legitimate search engine bots like Googlebot. The key is to ensure that your <code className="bg-muted px-1.5 py-0.5 rounded-sm">robots.txt</code> file explicitly *disallows* good bots from accessing the SpiteSpiral trap paths, while rule-ignoring scrapers proceed into it. We provide clear guidance on how to set this up, ensuring your valuable content remains perfectly indexable by search engines you care about. The target is bots that *don't* respect your rules.</p></>)
  },
  {
    question: "What exactly happens when a scraper enters the SpiteSpiral?",
    answer: (<><p>The scraper is led into an endlessly deep warren of dynamically structured pages, assembled on-the-fly by our Procedural Content Generation engine. Each page features unique, thematically coherent (but ultimately deceptive) text generated by our 'Nightmare Shovel' N-gram model, designed to appear valuable. These pages are served slowly and are filled with more links leading deeper into the trap. The goal is to consume the scraper's time, bandwidth, CPU, and storage, while polluting any data it collects with useless, subtly misleading information.</p></>)
  },
  {
    question: "What is 'Dynamic N-gram Text Generation' and why is it better?",
    answer: (<><p>Our system uses a sophisticated N-gram model trained on a massive, diverse corpus of real-world text. Our 'Nightmare Shovel' content engine then uses your 'fuel' (thematic seed phrases you can optionally provide, or we generate them) to guide the generator, creating unique paragraphs that are not only grammatically correct but also thematically coherent, making them far more deceptive than simple repeating text or basic LLM outputs.</p></>)
  },
  {
    question: "Is this just about \"spite\"? What's the tangible benefit for my business/website?",
    answer: (
      <>
        <p>While there's definitely satisfaction in outsmarting scrapers (that's our origin!), the tangible benefits are serious:</p>
        <ul className="list-disc pl-5 space-y-1 mt-2 text-foreground/80">
          <li><strong>Deterrence:</strong> Makes your site an unattractive and costly target for data thieves.</li>
          <li><strong>Resource Protection (Indirect):</strong> By tying up bad bots, you reduce the load they might otherwise put on your actual content servers.</li>
          <li><strong>Data Devaluation:</strong> Actively works to pollute datasets that might be used to train AI models on your (or similar) content without consent.</li>
          <li><strong>Competitive Edge:</strong> Makes it harder and more expensive for competitors to scrape your data for their advantage.</li>
        </ul>
      </>
    )
  },
  {
    question: "What kind of bots does SpiteSpiral target?",
    answer: (
      <>
        <p>SpiteSpiral primarily targets automated bots, AI crawlers, and data scrapers that:</p>
        <ul className="list-disc pl-5 space-y-1 mt-2 text-foreground/80">
          <li>Ignore <code className="bg-muted px-1.5 py-0.5 rounded-sm">robots.txt</code> directives.</li>
          <li>Are designed for large-scale, indiscriminate content harvesting.</li>
          <li>Are often used for AI model training, competitive data aggregation, or other forms of unauthorized data extraction.</li>
        </ul>
      </>
    )
  },
  {
    question: "Is it complicated to set up?",
    answer: (<><p>We aim for simplicity. The basic setup involves adding a specially crafted link to your website, pointing to our service. We provide clear instructions, including the crucial <code className="bg-muted px-1.5 py-0.5 rounded-sm">robots.txt</code> configurations to protect your SEO.</p></>)
  },
  {
    question: "What if they figure it out?",
    answer: (<><p>The beauty of our 'Nightmare Shovel' N-gram generated content and procedurally generated layouts is that it's much harder to create a simple "signature" for detection. While no trap is foolproof forever against the most sophisticated adversaries, SpiteSpiral is designed to be a constantly shifting, deeply frustrating, and resource-intensive quagmire. We aim to make the cost of "figuring it out" higher than the value of the data they're trying to steal from you.</p></>)
  },
  {
    question: "So, why the name SpiteSpiral?",
    answer: (
      <>
        <p><strong>The 'Spite':</strong> Let's be direct. There's a deep, justified frustration with AI crawlers and data scrapers that relentlessly exploit content without permission. The initial inspiration for tackling this problem head-on drew from the spirit of early honeypot systems. However, SpiteSpiral is now powered by our own proprietary Nightmare v2 engine, custom-built in Go from the ground up for superior performance and flexibility in this ongoing battle.</p>
        <p className="mt-2"><strong>The 'Spiral':</strong> This describes the sophisticated trap we spring. Misbehaving bots are lured into a maddening, recursive vortex of procedurally generated layouts filled with N-gram generated text, designed to exhaust their resources and hopelessly contaminate their data. It's a one-way trip to digital purgatory.</p>
        <p className="mt-2">Setting up an effective tarpit is complex, resource-intensive, and can backfire on your own site if not handled expertly. SpiteSpiral, built on a custom, high-performance Go-based platform, takes the fight to them, on our turf. We burn our CPU cycles, deploy advanced defenses, and minimise negative repercussions.</p>
        <p className="mt-2">Frankly, this ongoing battle of wits – this abstract, compute-based warfare – is what drives us. We are dedicated to relentlessly mutating and advancing SpiteSpiral, ensuring it remains a cutting-edge weapon to inflict maximum inefficiency and waste on unwanted scrapers.</p>
      </>
    )
  }
];


export default function HomePage() {
  const [isMounted, setIsMounted] = useState(false);
  const directTarpitUrl = "https://api.spitespiral.com/trap/a218a364-aec0-4e17-a218-321d59dd29d2";

  useEffect(() => {
    setIsMounted(true);
  }, []);

  return (
    <>
      {/* Invisible direct tarpit link for header area */}
      <a
        href={directTarpitUrl}
        rel="nofollow noopener noreferrer"
        aria-hidden="true"
        tabIndex={-1}
        style={{
          opacity: 0.01,
          position: 'absolute',
          left: '-9999px',
          top: '-9999px',
          fontSize: '1px',
          color: 'transparent',
          width: '1px',
          height: '1px',
          overflow: 'hidden',
        }}
        title="SpiteSpiral Internal Data - Homepage"
      >
        .
      </a>
      <div className="relative flex flex-col items-center justify-center min-h-screen bg-background text-foreground font-mono p-4 sm:p-6 md:p-8 selection:bg-primary selection:text-primary-foreground">
        {isMounted && (
            <div className="fixed inset-0 overflow-hidden z-0 flex items-center justify-center">
              <BrandLogoIcon
                  className="w-[500vw] h-[500vh] opacity-5 animate-spin-slow"
                  isPriority={false}
              />
            </div>
        )}

        <div className="relative z-10 text-center flex flex-col items-center w-full flex-grow">
          <div className="mb-4 transform transition-transform hover:scale-110 active:scale-95">
            <BrandLogoIcon className="w-56 h-56 md:w-72 md:h-72" isPriority={true} />
          </div>
          
          <div className="mb-10">
             <h1 className="text-5xl md:text-7xl font-black font-sans glitch-text tracking-wider">
              <span className="text-primary-foreground">Spite</span><span className="text-primary">Spiral</span>
            </h1>
             <p className="text-lg md:text-xl text-muted-foreground mt-2 max-w-xl md:max-w-2xl mx-auto">
              Active Defense Against Persistent AI Crawlers & Data Scrapers. Powered by our proprietary Nightmare v2 engine.
            </p>
          </div>

          <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-xl md:max-w-3xl leading-relaxed">
               Standard defenses like <code className="bg-muted px-1.5 py-0.5 rounded-sm">robots.txt</code> are routinely ignored by aggressive AI crawlers and data scrapers. SpiteSpiral, built on a custom, high-performance Go-based platform, offers a potent second line of defense. We don&apos;t just try to turn them away; we invite them into a digital labyrinth designed to waste their resources, pollute their datasets with thematically coherent, N-gram generated text, and make scraping your content an expensive, fruitless endeavor.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 mb-10">
              <Button
                asChild
                size="lg"
                variant="outline"
                className="px-10 py-6 text-lg text-accent border-accent hover:text-accent-foreground hover:bg-accent/90 transition-all duration-100 ease-in-out shadow-[0_0_15px_hsl(var(--accent)/0.5),_0_0_30px_hsl(var(--accent)/0.3)] hover:shadow-[0_0_20px_hsl(var(--accent)),_0_0_40px_hsl(var(--accent)/0.7)] rounded-lg border-b-4 border-accent/60 active:translate-y-0.5 active:border-b-2 active:[box-shadow:inset_0_3px_5px_rgba(0,0,0,0.3)] active:brightness-90"
              >
                <NextLink href="/login">Deploy Your Trap</NextLink>
              </Button>
              <Button
                asChild
                size="lg"
                variant="outline"
                className="px-10 py-6 text-lg text-accent border-accent hover:text-accent-foreground hover:bg-accent/90 transition-all duration-100 ease-in-out shadow-[0_0_15px_hsl(var(--accent)/0.5),_0_0_30px_hsl(var(--accent)/0.3)] hover:shadow-[0_0_20px_hsl(var(--accent)),_0_0_40px_hsl(var(--accent)/0.7)] rounded-lg border-b-4 border-accent/60 active:translate-y-0.5 active:border-b-2 active:[box-shadow:inset_0_3px_5px_rgba(0,0,0,0.3)] active:brightness-90"
              >
                <NextLink href="/demo/dashboard">View Live Demo</NextLink>
              </Button>
          </div>

          {/* Informational Cards Section - Now 2x2 Grid */}
          <div className="mt-10 mb-20 w-full max-w-5xl px-4 grid md:grid-cols-2 gap-6 text-left">
            <Card className="border-primary/30 shadow-lg shadow-primary/10 bg-card/80 backdrop-blur-sm flex flex-col h-full">
              <CardHeader className="p-6 flex items-center">
                <CardTitle className="text-2xl text-accent glitch-text min-h-12 flex items-center">The Problem: When Scrapers Ignore the Rules</CardTitle>
              </CardHeader>
              <CardContent className="text-foreground/80 space-y-3 flex-grow">
                  <p>Your valuable content, data, and intellectual property are prime targets for automated bots. Many of these scrapers brazenly ignore <code className="bg-muted px-1.5 py-0.5 rounded-sm text-xs">robots.txt</code> and bypass conventional blocking techniques, constantly draining your server resources and stealing your work for AI training models or competitive analysis. Simply blocking isn&apos;t enough for these persistent threats.</p>
                   <ul className="list-disc pl-5 space-y-2 mt-2 text-foreground/80">
                      <li><strong>Brazen Disregard for Rules:</strong> These scrapers frequently ignore <code className="bg-muted px-1.5 py-0.5 rounded-sm text-xs">robots.txt</code> directives, the established standard for bot etiquette. They are engineered to bypass common blocking techniques, making traditional defenses feel like sieves.</li>
                      <li><strong>Relentless Resource Drain:</strong> Unchecked scraping can overwhelm your server, consuming excessive bandwidth, CPU, and memory. This can lead to slower site performance for legitimate users, increased hosting costs, and even potential downtime.</li>
                      <li><strong>Theft for AI & Competitive Exploitation:</strong> Your original work, articles, images, product information, and pricing data are prime targets. This stolen information is then often fed into large AI training models without consent or used by competitors to gain an unfair advantage, diluting your brand and devaluing your efforts.</li>
                      <li><strong>Conventional Blocking is Often Insufficient:</strong> Static IP blocks, basic firewall rules, or simple rate limiting are often outmaneuvered by sophisticated scraping operations that use distributed networks and constantly changing identities. These persistent threats require a more dynamic and active countermeasure.</li>
                  </ul>
              </CardContent>
            </Card>

            <Card className="border-accent/30 shadow-lg shadow-accent/10 bg-card/80 backdrop-blur-sm flex flex-col h-full">
              <CardHeader className="p-6 flex items-center">
                <CardTitle className="text-2xl text-accent glitch-text min-h-12 flex items-center">The SpiteSpiral Solution: Active Deterrence & Data Devaluation</CardTitle>
              </CardHeader>
              <CardContent className="text-foreground/80 space-y-3 flex-grow">
                <p>SpiteSpiral isn&apos;t a passive shield; it&s an active trap powered by our Nightmare v2 engine. By strategically embedding a SpiteSpiral link, you redirect these rule-ignoring bots into a carefully constructed digital maze:</p>
                <ul className="list-disc pl-5 space-y-2 text-foreground/80">
                    <li><strong>Dynamic N-gram Text Generation:</strong> Our proprietary 'Nightmare Shovel' content engine uses a sophisticated N-gram model trained on a massive, diverse corpus. It generates unique, thematically coherent (yet deceptive) text, far more convincing and harder to detect than simple repeating patterns or basic LLM outputs.</li>
                    <li><strong>Procedural Content Generation (PCG):</strong> SpiteSpiral doesn't use static templates. Our Nightmare v2 engine acts as a 'Procedural Content Generator,' assembling a unique and complex website layout for every request. It combines headers, sidebars, main content blocks, and dynamic traps into a fractal explosion of unique pages, ensuring no two paths in the labyrinth are ever the same.</li>
                    <li><strong>Strategic Resource Drain:</strong> Each interaction is designed to be slow and demanding for the bot, consuming its CPU cycles, bandwidth, and time with an endless stream of unique pages and deep, recursive links.</li>
                    <li><strong>Proactive Data Devaluation:</strong> By feeding AI scrapers our N-gram generated noise, we aim to degrade the quality of their training data, making their efforts not only costly but counterproductive.</li>
                    <li><strong>SEO-Conscious Design:</strong> Implemented correctly (we&apos;ll show you how!), SpiteSpiral targets *only* misbehaving bots, leaving your standing with legitimate search engines like Google unharmed.</li>
                </ul>
                <div className="mt-4 pt-3 border-t border-border/50">
                  <h4 className="text-lg font-semibold text-primary mb-2">Beyond the Trap: Proactive Defense with API Access <span className="text-xs text-accent font-normal">(Coming Soon!)</span></h4>
                  <p className="text-foreground/80 mb-2">SpiteSpiral is evolving. Soon, you&apos;ll be able to:</p>
                  <ul className="list-disc pl-5 space-y-1 text-foreground/80">
                    <li><strong>Access Your Tarpit Data Programmatically:</strong> Integrate detailed logs and statistics from your *own* tarpit instances directly into your security workflows.</li>
                    <li><strong>Leverage Global Network Intelligence:</strong> Gain API access to anonymized, aggregated threat data from the *entire* SpiteSpiral network. Use this to proactively block known malicious actors *before* they even reach your site. This includes enhanced IP intelligence with ASN/network provider data.</li>
                  </ul>
                  <p className="text-foreground/80 mt-2">This creates a powerful feedback loop: actively block known threats identified by the network, and use your SpiteSpiral tarpit to catch, analyze, and contribute new threats back to the collective intelligence. Stay ahead of the curve.</p>
                </div>
              </CardContent>
            </Card>

            <Card className="border-primary/30 shadow-lg shadow-primary/10 bg-card/80 backdrop-blur-sm flex flex-col h-full">
              <CardHeader className="p-6 flex items-center">
                <CardTitle className="text-2xl text-accent glitch-text min-h-12 flex items-center">Why SpiteSpiral? Our Unique Approach</CardTitle>
              </CardHeader>
              <CardContent className="text-foreground/80 space-y-3 flex-grow">
                <p>Most bot solutions focus on *blocking*. SpiteSpiral, powered by our proprietary Nightmare v2 engine, focuses on **active engagement and consequence** for those that slip through or deliberately ignore your rules.</p>
                <ul className="list-disc pl-5 space-y-2 text-foreground/80">
                    <li><strong>Unique Trap-and-Drain Methodology:</strong> We turn your site into a sticky web for unwanted crawlers.</li>
                    <li><strong>Advanced N-gram Text Engine:</strong> Our 'Nightmare Shovel' creates highly deceptive and thematically coherent content to maximize data pollution.</li>
                    <li><strong>Procedurally Generated Layouts:</strong> Ensures infinite structural diversity in the trap, making detection extremely difficult.</li>
                    <li><strong>Cost-Amplification for Scrapers:</strong> We make scraping your data an expensive mistake.</li>
                    <li><strong>Aimed at Rule-Breakers:</strong> Designed for the bots that other systems miss or can&apos;t effectively stop without impacting legitimate traffic.</li>
                </ul>
              </CardContent>
            </Card>

            <Card className="border-accent/30 shadow-lg shadow-accent/10 bg-card/80 backdrop-blur-sm flex flex-col h-full">
              <CardHeader className="p-6 flex items-center">
                <CardTitle className="text-2xl text-accent glitch-text min-h-12 flex items-center">Who Needs SpiteSpiral?</CardTitle>
              </CardHeader>
              <CardContent className="text-foreground/80 space-y-3 flex-grow">
                <p>SpiteSpiral is for anyone tired of their content being exploited by aggressive, unauthorized scrapers:</p>
                <ul className="list-disc pl-5 space-y-2 text-foreground/80">
                    <li><strong>Businesses:</strong> Protect proprietary data, pricing strategies, and unique content. Prevent competitors from easily training AI models on your information.</li>
                    <li><strong>Creators & Artists:</strong> Safeguard your intellectual property and make it costly for AI to train on your original work without permission.</li>
                    <li><strong>Developers & Site Owners:</strong> Add a potent layer of defense against resource-draining bots that ignore common courtesies.</li>
                </ul>
              </CardContent>
            </Card>
          </div>

          {/* FAQ Section */}
          <div className="mt-10 mb-20 w-full max-w-4xl px-4">
            <Card className="border-primary/30 shadow-lg shadow-primary/10 bg-card/80 backdrop-blur-sm">
              <CardHeader className="p-6 text-center">
                <CardTitle className="text-4xl text-primary glitch-text">Frequently Asked Questions</CardTitle>
                <CardDescription className="text-muted-foreground mt-2">The Honest Truth</CardDescription>
              </CardHeader>
              <CardContent className="text-left text-foreground/80">
                <Accordion type="single" collapsible className="w-full">
                  {faqData.map((item, index) => (
                    <AccordionItem value={`item-${index + 1}`} key={index} className="border-primary/20">
                      <AccordionTrigger className="text-lg text-accent hover:text-primary hover:no-underline text-left py-5">
                        {item.question}
                      </AccordionTrigger>
                      <AccordionContent className="pb-4 pt-2 text-base leading-relaxed">
                        {typeof item.answer === 'string' ? <p>{item.answer}</p> : item.answer}
                      </AccordionContent>
                    </AccordionItem>
                  ))}
                </Accordion>
              </CardContent>
            </Card>
          </div>
        </div>

        <footer className="py-6 md:px-8 md:py-0 border-t border-primary/10 bg-card/50 relative z-20">
          <div className="container flex flex-col items-center justify-center gap-2 md:h-20 text-center">
            <NextLink href="/" className="flex items-center gap-2 group mb-2">
              <BrandLogoIcon className="h-8 w-8 text-primary" />
              <span className="text-sm font-semibold text-primary">SpiteSpiral</span>
            </NextLink>
            <NextLink href="/legal/licenses" className="text-xs text-muted-foreground/70 hover:text-accent animate-link-glow">
              Licenses &amp; Acknowledgements
            </NextLink>
            <p className="text-xs text-muted-foreground/70">
              © {new Date().getFullYear()} SpiteSpiral. Trap with malice.
            </p>
          </div>
           {/* Invisible redirect tarpit link for footer area */}
           <div aria-hidden="true" style={{ position: 'absolute', left: '-9999px', top: '-9999px', opacity: 0, width: '1px', height: '1px', overflow: 'hidden' }}>
            <a href="/sneedsfeedandseed/" title="Internal Archive Redirect - Homepage" style={{ fontSize: '1px', color: 'transparent', display: 'inline-block' }}>.</a>
          </div>
        </footer>
      </div>
    </>
  );
}


    
