
'use client';

import NextLink from 'next/link';
import { Button } from '@/components/ui/button';
import BrandLogoIcon from '@/components/icons/BrandLogoIcon';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";
import { useEffect, useState } from 'react';
import { cn } from '@/lib/utils';

const faqData = [
  {
    question: "How is SpiteSpiral different from `robots.txt` or my firewall/WAF?",
    answer: "Robots.txt is a request, not a command, and many AI scrapers and malicious bots ignore it. Firewalls and WAFs are great for blocking known threats or patterns, but persistent, adaptive scrapers can often find ways around them. SpiteSpiral is what happens *next*. We're designed to specifically target and neutralize the bots that bypass these first lines of defense, making their journey not just blocked, but incredibly inefficient and counterproductive by feeding them resource-intensive, LLM-generated junk data."
  },
  {
    question: "Will using SpiteSpiral hurt my website's SEO?",
    answer: "Not when implemented correctly. SpiteSpiral is designed to be invisible to legitimate search engine bots like Googlebot. The key is to ensure that your `robots.txt` file explicitly *disallows* good bots from accessing the SpiteSpiral trap paths, while rule-ignoring scrapers proceed into it. We provide clear guidance on how to set this up, ensuring your valuable content remains perfectly indexable by search engines you care about. The target is bots that *don't* respect your rules."
  },
  {
    question: "What exactly happens when a scraper enters the SpiteSpiral?",
    answer: "The scraper is led into an endlessly deep warren of dynamically generated pages. Each page features unique, plausible-sounding (but ultimately nonsensical) text generated by our integrated LLM, designed to appear valuable. These pages are served slowly and are filled with more links leading deeper into the trap. The goal is to consume the scraper's time, bandwidth, CPU, and storage, while polluting any data it collects with useless, subtly misleading information."
  },
  {
    question: "What is \"LLM-Powered Intelligent Babble\" and why is it better?",
    answer: "Instead of simple repetitive text, SpiteSpiral uses small but sophisticated Large Language Models (LLMs) to generate unique, grammatically correct, and contextually-aware (based on fake URL paths) nonsense. This \"intelligent babble\" is much harder for scrapers to identify as a trap compared to basic generated content. It's more likely to be ingested into their datasets, effectively devaluing the information they're trying to steal."
  },
  {
    question: "Is this just about \"spite\"? What's the tangible benefit for my business/website?",
    answer: (
      <>
        <p>While there's definitely satisfaction in outsmarting scrapers (that's our origin!), the tangible benefits are serious:</p>
        <ul className="list-disc pl-5 space-y-1 mt-2 text-foreground/80">
          <li><strong>Deterrence:</strong> Makes your site an unattractive and costly target for data thieves.</li>
          <li><strong>Resource Protection (Indirect):</strong> By tying up bad bots, you reduce the load they might otherwise put on your actual content servers.</li>
          <li><strong>Data Devaluation:</strong> Actively works to pollute datasets that might be used to train AI models on your (or similar) content without consent.</li>
          <li><strong>Competitive Edge:</strong> Makes it harder and more expensive for competitors to scrape your data for their advantage.</li>
        </ul>
      </>
    )
  },
  {
    question: "What kind of bots does SpiteSpiral target?",
    answer: (
      <>
        <p>SpiteSpiral primarily targets automated bots, AI crawlers, and data scrapers that:</p>
        <ul className="list-disc pl-5 space-y-1 mt-2 text-foreground/80">
          <li>Ignore `robots.txt` directives.</li>
          <li>Are designed for large-scale, indiscriminate content harvesting.</li>
          <li>Are often used for AI model training, competitive data aggregation, or other forms of unauthorized data extraction.</li>
        </ul>
      </>
    )
  },
  {
    question: "Is it complicated to set up?",
    answer: "We aim for simplicity. The basic setup involves adding a specially crafted link to your website, pointing to our service. We provide clear instructions, including the crucial `robots.txt` configurations to protect your SEO."
  },
  {
    question: "What if they figure it out?",
    answer: "The beauty of LLM-generated content and dynamically structured pages is that it's much harder to create a simple \"signature\" for detection. While no trap is foolproof forever against the most sophisticated adversaries, SpiteSpiral is designed to be a constantly shifting, deeply frustrating, and resource-intensive quagmire. We aim to make the cost of \"figuring it out\" higher than the value of the data they're trying to steal from you."
  },
  {
    question: "So, why the name SpiteSpiral?",
    answer: (
      <>
        <p><strong>The 'Spite':</strong> Let's be direct. There's a deep, justified frustration with AI crawlers and data scrapers that relentlessly exploit content without permission. This sentiment is shared by many, including the visionary behind Nepenthes—the powerful, MIT-licensed tarpit codebase SpiteSpiral proudly evolves. Our 'Spite' is a commitment to channel that energy into decisive action against these intrusive practices.</p>
        <p className="mt-2"><strong>The 'Spiral':</strong> This describes the sophisticated trap we spring. Misbehaving bots are lured into a maddening, recursive vortex of LLM-generated pages, designed to exhaust their resources and hopelessly contaminate their data. It's a one-way trip to digital purgatory.</p>
        <p className="mt-2">Setting up an effective tarpit is complex, resource-intensive, and can backfire on your own site if not handled expertly. SpiteSpiral takes the fight to them, on our turf. We burn our CPU cycles, deploy advanced defenses, and minimise negative repercussions.</p>
        <p className="mt-2">Frankly, this ongoing battle of wits – this abstract, compute-based warfare – is what drives us. We are dedicated to relentlessly mutating and advancing SpiteSpiral, ensuring it remains a cutting-edge weapon to inflict maximum inefficiency and waste on unwanted scrapers.</p>
      </>
    )
  }
];


export default function HomePage() {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  return (
    <div className="relative flex flex-col items-center justify-center min-h-screen bg-background text-foreground font-mono p-8 selection:bg-primary selection:text-primary-foreground">
      {isMounted && (
          <div className="absolute inset-0 overflow-hidden z-0 flex items-center justify-center">
            <BrandLogoIcon
                className="w-[500vw] h-[500vh] opacity-5 animate-spin-slow"
                isPriority={false}
            />
          </div>
      )}

      <div className="relative z-10 text-center flex flex-col items-center w-full flex-grow">
        <div className="mb-4 transform transition-transform hover:scale-110 active:scale-95">
          <BrandLogoIcon className="w-56 h-56 md:w-72 md:h-72" isPriority={true} />
        </div>
        
        <div className="mb-10">
          <h1 className="text-5xl md:text-7xl font-black font-sans glitch-text tracking-wider">
            <span className="text-primary-foreground">Spite</span><span className="text-primary">Spiral</span>
          </h1>
          <p className="text-lg md:text-xl text-muted-foreground mt-2 max-w-xl md:max-w-2xl mx-auto">
            Active Defense Against Persistent AI Crawlers & Data Scrapers.
          </p>
        </div>

        <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-xl md:max-w-3xl leading-relaxed">
          Standard defenses like <code>robots.txt</code> are routinely ignored by aggressive AI crawlers and data scrapers. SpiteSpiral offers a potent second line of defense. We don&apos;t just try to turn them away; we invite them into a digital labyrinth designed to waste their resources, pollute their datasets with LLM-generated &apos;intelligent babble,&apos; and make scraping your content an expensive, fruitless endeavor.
        </p>
        <div className="flex flex-col sm:flex-row gap-4 mb-20">
            <Button
              asChild
              size="lg"
              className="px-10 py-6 text-lg bg-primary text-primary-foreground hover:bg-accent hover:text-accent-foreground transition-all duration-100 ease-in-out shadow-[0_0_15px_hsl(var(--primary)),_0_0_30px_hsl(var(--primary)/0.7)] hover:shadow-[0_0_20px_hsl(var(--accent)),_0_0_40px_hsl(var(--accent)/0.7)] rounded-lg border-b-4 border-primary/60 active:translate-y-0.5 active:border-b-2 active:[box-shadow:inset_0_3px_5px_rgba(0,0,0,0.3)] active:brightness-90"
            >
              <NextLink href="/login">Deploy Your Trap</NextLink>
            </Button>
            <Button
              asChild
              size="lg"
              variant="outline"
              className="px-10 py-6 text-lg text-accent border-accent hover:text-accent-foreground hover:bg-accent/90 transition-all duration-100 ease-in-out shadow-[0_0_15px_hsl(var(--accent)/0.5),_0_0_30px_hsl(var(--accent)/0.3)] hover:shadow-[0_0_20px_hsl(var(--accent)),_0_0_40px_hsl(var(--accent)/0.7)] rounded-lg border-b-4 border-accent/60 active:translate-y-0.5 active:border-b-2 active:[box-shadow:inset_0_3px_5px_rgba(0,0,0,0.2)] active:brightness-90"
            >
              <NextLink href="/demo/dashboard">View Live Demo</NextLink>
            </Button>
        </div>

        {/* Informational Cards Section */}
        <div className="mt-10 mb-20 w-full max-w-5xl px-4 grid md:grid-cols-2 gap-6 text-left">
          <Card className="border-primary/30 shadow-lg shadow-primary/10 bg-card/80 backdrop-blur-sm">
            <CardHeader className="p-6 flex items-center min-h-12">
              <CardTitle className="text-2xl text-accent glitch-text min-h-12 flex items-center">The Problem: When Scrapers Ignore the Rules</CardTitle>
            </CardHeader>
            <CardContent className="text-foreground/80 space-y-3">
              <p>Your valuable content, data, and intellectual property are prime targets for automated bots. Many of these scrapers brazenly ignore <code>robots.txt</code> and bypass conventional blocking techniques, constantly draining your server resources and stealing your work for AI training models or competitive analysis. Simply blocking isn&apos;t enough for these persistent threats.</p>
            </CardContent>
          </Card>

          <Card className="border-accent/30 shadow-lg shadow-accent/10 bg-card/80 backdrop-blur-sm">
            <CardHeader className="p-6 flex items-center min-h-12">
              <CardTitle className="text-2xl text-accent glitch-text min-h-12 flex items-center">The SpiteSpiral Solution: Active Deterrence & Data Devaluation</CardTitle>
            </CardHeader>
            <CardContent className="text-foreground/80 space-y-3">
              <p>SpiteSpiral isn&apos;t a passive shield; it&apos;s an active trap. By strategically embedding a SpiteSpiral link, you redirect these rule-ignoring bots into a carefully constructed digital maze:</p>
              <ul className="list-disc pl-5 space-y-2 text-foreground/80">
                  <li><strong>LLM-Powered Deception:</strong> Our core uses advanced, small language models (like DistilGPT-2) to generate vast quantities of unique, contextually plausible (yet ultimately nonsensical) content. This &apos;intelligent babble&apos; is far more convincing than simple repeated text, making it harder for scrapers to detect the trap and more likely to be ingested into their datasets.</li>
                  <li><strong>Strategic Resource Drain:</strong> Each interaction is designed to be slow and demanding for the bot, consuming its CPU cycles, bandwidth, and time with an endless stream of unique pages and deep, recursive links.</li>
                  <li><strong>Proactive Data Devaluation:</strong> By feeding AI scrapers our LLM-generated noise, we aim to degrade the quality of their training data, making their efforts not only costly but counterproductive.</li>
                  <li><strong>SEO-Conscious Design:</strong> Implemented correctly (we&apos;ll show you how!), SpiteSpiral targets *only* misbehaving bots, leaving your standing with legitimate search engines like Google unharmed.</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="border-primary/30 shadow-lg shadow-primary/10 bg-card/80 backdrop-blur-sm">
            <CardHeader className="p-6 flex items-center min-h-12">
              <CardTitle className="text-2xl text-accent glitch-text min-h-12 flex items-center">Why SpiteSpiral? Our Unique Approach</CardTitle>
            </CardHeader>
            <CardContent className="text-foreground/80 space-y-3">
              <p>Most bot solutions focus on *blocking*. SpiteSpiral focuses on **active engagement and consequence** for those that slip through or deliberately ignore your rules.</p>
              <ul className="list-disc pl-5 space-y-2 text-foreground/80">
                  <li><strong>Unique Trap-and-Drain Methodology:</strong> We turn your site into a sticky web for unwanted crawlers.</li>
                  <li><strong>Sophisticated LLM Content Generation:</strong> Makes our traps more believable and our data pollution more effective.</li>
                  <li><strong>Cost-Amplification for Scrapers:</strong> We make scraping your data an expensive mistake.</li>
                  <li><strong>Aimed at Rule-Breakers:</strong> Designed for the bots that other systems miss or can&apos;t effectively stop without impacting legitimate traffic.</li>
              </ul>
            </CardContent>
          </Card>

          <Card className="border-accent/30 shadow-lg shadow-accent/10 bg-card/80 backdrop-blur-sm">
            <CardHeader className="p-6 flex items-center min-h-12">
              <CardTitle className="text-2xl text-accent glitch-text min-h-12 flex items-center">Who Needs SpiteSpiral?</CardTitle>
            </CardHeader>
            <CardContent className="text-foreground/80 space-y-3">
              <p>SpiteSpiral is for anyone tired of their content being exploited by aggressive, unauthorized scrapers:</p>
              <ul className="list-disc pl-5 space-y-2 text-foreground/80">
                  <li><strong>Businesses:</strong> Protect proprietary data, pricing strategies, and unique content. Prevent competitors from easily training AI models on your information.</li>
                  <li><strong>Creators & Artists:</strong> Safeguard your intellectual property and make it costly for AI to train on your original work without permission.</li>
                  <li><strong>Developers & Site Owners:</strong> Add a potent layer of defense against resource-draining bots that ignore common courtesies.</li>
              </ul>
            </CardContent>
          </Card>
        </div>

        {/* FAQ Section */}
        <div className="mt-10 mb-20 w-full max-w-4xl px-4">
          <Card className="border-primary/30 shadow-lg shadow-primary/10 bg-card/80 backdrop-blur-sm">
            <CardHeader className="p-6 text-center">
              <CardTitle className="text-4xl text-primary glitch-text">Frequently Asked Questions</CardTitle>
              <CardDescription className="text-muted-foreground mt-2">The Honest Truth</CardDescription>
            </CardHeader>
            <CardContent className="text-left text-foreground/80">
              <Accordion type="single" collapsible className="w-full">
                {faqData.map((item, index) => (
                  <AccordionItem value={`item-${index + 1}`} key={index} className="border-primary/20">
                    <AccordionTrigger className="text-lg text-accent hover:text-primary hover:no-underline text-left py-5">
                      {item.question}
                    </AccordionTrigger>
                    <AccordionContent className="pb-4 pt-2 text-base leading-relaxed">
                      {typeof item.answer === 'string' ? <p>{item.answer}</p> : item.answer}
                    </AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </CardContent>
          </Card>
        </div>
      </div>

      {/* Demo Tracking Pixel */}
      <img src="https://api.spitespiral.com/trap/38e19a7e-1a3f-4bf0-b83f-edd7efe6fceb" width="1" height="1" alt="" style={{border:0, position:"absolute", left:"-9999px"}} aria-hidden="true" loading="eager" />

      <footer className="py-6 md:px-8 md:py-0 border-t border-primary/10 bg-card/50 mt-auto">
        <div className="container flex flex-col items-center justify-center gap-2 md:h-20 text-center">
          <NextLink href="/" className="flex items-center gap-2 group mb-2">
            <BrandLogoIcon className="h-8 w-8 text-primary" />
            <span className="text-sm font-semibold text-primary">SpiteSpiral</span>
          </NextLink>
          <NextLink href="/legal/licenses" className="text-xs text-muted-foreground/70 hover:text-accent animate-link-glow">
            Licenses & Acknowledgements
          </NextLink>
          <p className="text-xs text-muted-foreground/70">
            © {new Date().getFullYear()} SpiteSpiral. Trap with malice.
          </p>
        </div>
      </footer>
    </div>
  );
}
